CREATE OR REPLACE PACKAGE PA_SUPERVISOR IS
    FUNCTION CO_TOTINACTIVOS RETURN SYS_REFCURSOR;
    PROCEDURE EL_PERFIL (XAPODO IN VARCHAR2);
END PA_SUPERVISOR;
/
CREATE OR REPLACE PACKAGE PA_USUARIO IS
    FUNCTION CO_JUGADORES RETURN SYS_REFCURSOR;
    FUNCTION CO_EQUIPOS RETURN SYS_REFCURSOR;
    FUNCTION CO_COMPETENCIAS RETURN SYS_REFCURSOR;
    PROCEDURE AD_PERFIL (XNOMBRE IN VARCHAR2, XAPELLIDO IN VARCHAR2, XFECHANACI IN DATE, XCORREO IN VARCHAR2, XAPODO IN VARCHAR2, XCONTRASEÑA IN VARCHAR2);
    PROCEDURE MO_NOMBREP (XAPODO IN VARCHAR2, XNOMBRE IN VARCHAR2, XAPELLIDO IN VARCHAR2);
    PROCEDURE MO_CORREOP (XAPODO IN VARCHAR2, XCORREO IN VARCHAR2);
    PROCEDURE MO_APODOP (XAPODO IN VARCHAR2, NUEVO IN VARCHAR2);
END PA_USUARIO;
/
CREATE OR REPLACE PACKAGE PC_ORGANIZADOR IS
    PROCEDURE AD_COMPETENCIAS(XNOMBRE IN VARCHAR2, XID_VID IN NUMBER, XID_EQUI IN VARCHAR2, XRESULTADO IN XMLTYPE, XINICIO IN DATE, XFECHA_G IN DATE);
    FUNCTION CO_COMPETENCIAS RETURN SYS_REFCURSOR;
END PC_ORGANIZADOR;
/
CREATE OR REPLACE PACKAGE PC_DUEÑO_EQUIPO IS
    PROCEDURE AD_EQUIPOS(XNOMBRE IN VARCHAR2, XFUNDACION IN DATE, XREGION IN VARCHAR2, XWEB IN VARCHAR2, COACH IN VARCHAR2, XESTADO IN VARCHAR2 );
    PROCEDURE MO_COACHES(XNOMBRE IN VARCHAR2, XAPODO IN VARCHAR2);
    PROCEDURE MO_NOMBRES(XNOMBRE IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_PAGINAS(XNOMBRE IN VARCHAR2, XWEB IN VARCHAR2);
    PROCEDURE MO_PATROCINADORES(XNOMBRE IN VARCHAR2, NOMBREPAT IN VARCHAR2);
    FUNCTION CO_EQUIPOS RETURN SYS_REFCURSOR;
    PROCEDURE AD_JUGADORES(XNOMBRE IN VARCHAR2,XAPELLIDO IN VARCHAR2,XAPODO IN VARCHAR2,XEDAD IN NUMBER,XNACIONALIDAD IN VARCHAR2,XACTIVO IN CHAR,XID_EQUI IN VARCHAR2);
    FUNCTION CO_JUGADORES RETURN SYS_REFCURSOR;
    FUNCTION CO_COACHES RETURN SYS_REFCURSOR;
END PC_DUEÑO_EQUIPO;
/
CREATE OR REPLACE PACKAGE PC_COACH IS
    PROCEDURE AD_COACHES(XNOMBRE IN VARCHAR2,XAPELLIDO IN VARCHAR2,XAPODO IN VARCHAR2,XEDAD IN NUMBER,XNACIONALIDAD IN VARCHAR2);
    PROCEDURE MO_APODOC(XAPODO IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_EDADC(XAPODO IN VARCHAR2,XEDAD IN NUMBER);
    FUNCTION CO_COACHES RETURN SYS_REFCURSOR;
END PC_COACH;
/
CREATE OR REPLACE PACKAGE PC_PATROCINADOR IS
    PROCEDURE AD_PATROCINADORES(XNOMBRE IN VARCHAR2,XWEB IN VARCHAR2);
    PROCEDURE MO_WEBP(XWEB IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_NOMBREP(XWEB IN VARCHAR2,NUEVO IN VARCHAR2);
END PC_PATROCINADOR;
    