CREATE OR REPLACE PACKAGE BODY PA_SUPERVISOR IS
    FUNCTION CO_TOTINACTIVOS RETURN SYS_REFCURSOR  IS CO_TOT SYS_REFCURSOR;
    BEGIN
    OPEN CO_TOT FOR
        SELECT COUNT(*) FROM CONSULTAS WHERE (SYSDATE-FECHA) >= (5*365);
    RETURN CO_TOT;
    END CO_TOTINACTIVOS;
    
    PROCEDURE EL_PERFIL (XAPODO IN VARCHAR2) IS
    BEGIN
        DELETE FROM USUARIOS WHERE APODO=XAPODO;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo eliminar el usuario');
    END;
END PA_SUPERVISOR;
/
CREATE OR REPLACE PACKAGE BODY PA_USUARIO IS
    FUNCTION CO_JUGADORES RETURN SYS_REFCURSOR  IS CO_JU SYS_REFCURSOR;
    BEGIN
    OPEN CO_JU FOR
        SELECT NOMBRE, APELLIDO, APODO, EDAD, NACIONALIDAD, ROL, ACTIVO, INGRESO FROM JUGADORES;
    RETURN CO_JU;
    END CO_JUGADORES;
    
    FUNCTION CO_EQUIPOS RETURN SYS_REFCURSOR  IS CO_EQ SYS_REFCURSOR;
    BEGIN
        OPEN CO_EQ FOR
            SELECT NOMBRE, FUNDACION,REGION,WEB,ESTADO INGRESO FROM EQUIPOS;
        RETURN CO_EQ;
    END CO_EQUIPOS;
    FUNCTION CO_COMPETENCIAS RETURN SYS_REFCURSOR  IS CO_COM SYS_REFCURSOR;
    BEGIN
    OPEN CO_COM FOR
        SELECT NOMBRE, LUGAR,INICIO,REGION,FECHA_G,RESULTADO INGRESO FROM COMPETENCIAS;
    RETURN CO_COM;
    END CO_COMPETENCIAS;
    
    PROCEDURE AD_PERFIL (XNOMBRE IN VARCHAR2, XAPELLIDO IN VARCHAR2, XFECHANACI IN DATE, XCORREO IN VARCHAR2, XAPODO IN VARCHAR2, XCONTRASEÑA IN VARCHAR2) IS
    BEGIN
        INSERT INTO USUARIOS (NOMBRE, CORREO, APODO, FECHANACI, APELLIDO, CONTRASEÑA) VALUES (XNOMBRE, XCORREO, XAPODO, XFECHANACI, XAPELLIDO, XCONTRASEÑA);
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo realizar el registro');
    END;
    
    PROCEDURE MO_NOMBREP (XAPODO IN VARCHAR2, XNOMBRE IN VARCHAR2, XAPELLIDO IN VARCHAR2) IS
    BEGIN
        UPDATE USUARIOS SET NOMBRE=XNOMBRE, APELLIDO=XAPELLIDO WHERE APODO=XAPODO;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo modificar el nombre');
    END;
    PROCEDURE MO_CORREOP (XAPODO IN VARCHAR2, XCORREO IN VARCHAR2) IS
    BEGIN
        UPDATE USUARIOS SET CORREO=XCORREO WHERE APODO=XAPODO;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo modificar el correo');
    END;
    PROCEDURE MO_APODOP (XAPODO IN VARCHAR2, NUEVO IN VARCHAR2) IS
    BEGIN
        UPDATE USUARIOS SET APODO=NUEVO WHERE APODO=XAPODO;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo modificar el apodo');
    END;
END PA_USUARIO;
/
CREATE OR REPLACE PACKAGE BODY PC_ORGANIZADOR IS
    PROCEDURE AD_COMPETENCIAS (XNOMBRE IN VARCHAR2, XID_VID IN NUMBER, XID_EQUI IN VARCHAR2, XRESULTADO IN XMLTYPE, XINICIO IN DATE, XFECHA_G IN DATE) IS
    BEGIN
        INSERT INTO COMPETENCIAS (NOMBRE, ID_VID, ID_EQUI, RESULTADO, INICIO, FECHA_G) VALUES (XNOMBRE, XID_VID, XID_EQUI, XRESULTADO, XINICIO, XFECHA_G);
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo insertar la competencia');
    END;
    FUNCTION CO_COMPETENCIAS RETURN SYS_REFCURSOR  IS CO_COM SYS_REFCURSOR;
    BEGIN
    OPEN CO_COM FOR
        SELECT NOMBRE, LUGAR,INICIO,REGION,FECHA_G,RESULTADO INGRESO FROM COMPETENCIAS;
    RETURN CO_COM;
    END CO_COMPETENCIAS;
END PC_ORGANIZADOR;
/
CREATE OR REPLACE PACKAGE BODY PC_DUEÑO_EQUIPO IS
    PROCEDURE AD_EQUIPOS (XNOMBRE IN VARCHAR2, XFUNDACION IN DATE, XREGION IN VARCHAR2, XWEB IN VARCHAR2, COACH IN VARCHAR2, XESTADO IN VARCHAR2 ) IS
    X NUMBER;
    BEGIN
        SELECT ID INTO X FROM COACHES WHERE APODO=COACH; 
        INSERT INTO EQUIPOS (NOMBRE, FUNDACION, REGION, WEB, ID_COA, ESTADO) VALUES (XNOMBRE, XFUNDACION, XREGION, XWEB, X,'1');
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo insertar el equipo');
    END;
    
    PROCEDURE MO_COACH(XNOMBRE IN VARCHAR2 , XAPODO IN VARCHAR2) IS
    X NUMBER;
    BEGIN
        SELECT ID INTO X FROM COACHES WHERE NOMBRE=XNOMBRE;
        UPDATE EQUIPOS SET ID_COA=X WHERE ID_COA=X;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo actualizar el coach del equipo');
    END;
    PROCEDURE MO_NOMBRES(XNOMBRE IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_NOMBRES(XNOMBRE IN VARCHAR2, NUEVO IN VARCHAR2) IS
    BEGIN
        UPDATE EQUIPOS SET NOMBRE=NUEVO WHERE NOMBRE=XNOMBRE;
        COMMIT;
        EXCEPTION
        WHEN OTHERS THEN
        ROLLBACK;
        RAISE_APPLICATION_ERROR(-20001, 'No se pudo modificar el nombre del equipo');
    END;
    PROCEDURE MO_PAGINAS(XNOMBRE IN VARCHAR2, XWEB IN VARCHAR2);
    PROCEDURE MO_PATROCINADORES(XNOMBRE IN VARCHAR2, NOMBREPAT IN VARCHAR2);
    FUNCTION CO_EQUIPOS RETURN SYS_REFCURSOR;
    PROCEDURE AD_JUGADORES(XNOMBRE IN VARCHAR2,XAPELLIDO IN VARCHAR2,XAPODO IN VARCHAR2,XEDAD IN NUMBER,XNACIONALIDAD IN VARCHAR2,XACTIVO IN CHAR,XID_EQUI IN VARCHAR2);
    FUNCTION CO_JUGADORES RETURN SYS_REFCURSOR;
    FUNCTION CO_COACHES RETURN SYS_REFCURSOR;
END PC_DUEÑO_EQUIPO;
/
CREATE OR REPLACE PACKAGE PC_COACH IS
    PROCEDURE AD_COACHES(XNOMBRE IN VARCHAR2,XAPELLIDO IN VARCHAR2,XAPODO IN VARCHAR2,XEDAD IN NUMBER,XNACIONALIDAD IN VARCHAR2);
    PROCEDURE MO_APODOC(XAPODO IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_EDADC(XAPODO IN VARCHAR2,XEDAD IN NUMBER);
    FUNCTION CO_COACHES RETURN SYS_REFCURSOR;
END PC_COACH;
/
CREATE OR REPLACE PACKAGE PC_PATROCINADOR IS
    PROCEDURE AD_PATROCINADORES(XNOMBRE IN VARCHAR2,XWEB IN VARCHAR2);
    PROCEDURE MO_WEBP(XWEB IN VARCHAR2, NUEVO IN VARCHAR2);
    PROCEDURE MO_NOMBREP(XWEB IN VARCHAR2,NUEVO IN VARCHAR2);
END PC_PATROCINADOR;
    